<a href="https://colab.research.google.com/github/junhoo01/Pytorch_tutorial/blob/main/8.%20Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
#Scala

d = np.array(5)
#dim => 텐서의 차원, 축(axis)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 0
텐서의 크기(shape) : ()


In [8]:
#Vector

d = np.array([1, 2, 3, 4])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 1
텐서의 크기(shape) : (4,)


In [9]:
#Matrix

# 3행 4열의 행렬
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 2
텐서의 크기(shape) : (3, 4)


In [10]:
#3D Tensor

d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)
#Matrix가 2개 => 3*5 matrix ==> (2,3,5)

텐서의 차원 : 3
텐서의 크기(shape) : (2, 3, 5)


In [11]:
#3D Tensor => 주로 문장이나 문서, 뉴스기사등의 텍스트
#(Samples, Timesteps, Word_dim)

#3D Tensor를 배열로 합치면 4D Tensor
#4D Tensor => 5D Tensor

In [12]:
##########################################

#Computation

##########################################

In [13]:
import numpy as np

In [14]:
#Vectors
#그냥 +,-로 하면 생각하는 벡터 연산

A = np.array([8, 4, 5])
B = np.array([1, 2, 3])
print('두 벡터의 합 :',A+B)
print('두 벡터의 차 :',A-B)

두 벡터의 합 : [9 6 8]
두 벡터의 차 : [7 2 2]


In [15]:
#Matrix
#그냥 +,-로 하면 생각하는 행렬 연

A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print('두 행렬의 합 :')
print(A + B)
print('두 행렬의 차 :')
print(A - B)

두 행렬의 합 :
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 :
[[ 5 14 23 32]
 [49 58 67 76]]


In [16]:
#Innner Product
#np.dot으로 시행

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('두 벡터의 내적 :',np.dot(A, B))

두 벡터의 내적 : 32


In [17]:
#행렬곱1 => matmul사용
#뭐 m*n 행렬과 곱할려면 n*x 행렬과 곱해야한다 (n값 저게 같아야함)

A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A, B))

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]


In [18]:
#Linear Regression식도 weight와 parameter의 곱으로 생각할 수 있고,
#Data가 많아지면 행렬과 벡터의 곱으로 생각할 수 도 있다.

In [19]:
#각각의 Data를 Sample이라고 하고
#각각의 독립변수(parameter)를 feature라고 한다.