<a href="https://colab.research.google.com/github/junhoo01/Pytorch_tutorial/blob/main/nn_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [86]:
torch.manual_seed(1)

In [87]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [88]:
# nn.Linear()함수로 선형 회귀 모델을 받아오기 (이전과 다르게 직접 선언 X)
# 입력 차원과 출력 차원을 인수로 차례로 받음
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
# input_dim=1, output_dim=1 ==> 하나의 입력에 대해서 하나의 출력
model = nn.Linear(1,1)

In [89]:
# 가설은 aX + b 의 형태로
# 가중치 W와 편향 b가 저장되어 있다.
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [90]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [91]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    # nn.Linear을 통해 생성한 모델
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [92]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# 정답 함수가 y = 2x
#입력이 4이므로 y가 8이 나와야 한
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [93]:
print(list(model.parameters()))
# W가 2에 가깝고 b가 0에 가까운것을 알 수 있다.

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [94]:
#############################################

# Multivariate Linear Regression

#############################################

In [95]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [96]:
torch.manual_seed(1)

In [97]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [98]:
#입력이 3개 출력이 1개 => 입력 차원:3 / 출력 차원:1
model = nn.Linear(3,1)


In [99]:
print(list(model.parameters()))
# parameter들이 list로 저장되어 있음

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [100]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [101]:
######################################

# learning rate가 커서 기울기가 발산!

######################################


# Gradient Decent 2000 epoch 진행
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  # 예측치
  prediction = model(x_train)

  # 오차
  cost = F.mse_loss(prediction, y_train)
  # 파이토치의 mean square error 사용


  #weight 업데이트
  #초기화
  optimizer.zero_grad()
  #미분
  cost.backward()
  #업데이트
  optimizer.step()

  if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: nan
Epoch  200/2000 Cost: nan
Epoch  300/2000 Cost: nan
Epoch  400/2000 Cost: nan
Epoch  500/2000 Cost: nan
Epoch  600/2000 Cost: nan
Epoch  700/2000 Cost: nan
Epoch  800/2000 Cost: nan
Epoch  900/2000 Cost: nan
Epoch 1000/2000 Cost: nan
Epoch 1100/2000 Cost: nan
Epoch 1200/2000 Cost: nan
Epoch 1300/2000 Cost: nan
Epoch 1400/2000 Cost: nan
Epoch 1500/2000 Cost: nan
Epoch 1600/2000 Cost: nan
Epoch 1700/2000 Cost: nan
Epoch 1800/2000 Cost: nan
Epoch 1900/2000 Cost: nan
Epoch 2000/2000 Cost: nan


In [102]:
torch.manual_seed(1)

In [103]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [104]:
#입력이 3개 출력이 1개 => 입력 차원:3 / 출력 차원:1
model = nn.Linear(3,1)

In [105]:
print(list(model.parameters()))
# parameter들이 list로 저장되어 있음

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [106]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [107]:
#learning rate를 적절히 조정 => 기울기 폭주가 일어나지 않


# Gradient Decent 2000 epoch 진행


nb_epochs = 2000
for epoch in range(nb_epochs+1):

  # 예측치
  prediction = model(x_train)

  # 오차
  cost = F.mse_loss(prediction, y_train)
  # 파이토치의 mean square error 사용


  #weight 업데이트
  #초기화
  optimizer.zero_grad()
  #미분
  cost.backward()
  #업데이트
  optimizer.step()

  if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [108]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [109]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
